num = int(input('Digite um número:'))
print(f'{num}x1= {num*1}\n'
      f'{num}x2= {num*2}\n'
      f'{num}x3= {num*3}\n'
      f'{num}x4= {num*4}\n'
      f'{num}x5= {num*5}\n'
      f'{num}x6= {num*6}\n'
      f'{num}x7= {num*7}\n'
      f'{num}x8= {num*8}\n'
      f'{num}x9= {num*9}\n'
      f'{num}x10= {num*10}\n')
